services:
  raspi-finance-react:
    image: raspi-finance-react:2.0.99
    hostname: hornsup-react
    container_name: raspi-finance-react
    restart: always
    build:
      context: ./
      args:
        TIMEZONE: America/Chicago
      dockerfile: Containerfile
    ports:
      - "3000:443"
    extra_hosts:
      - "hornsup:${HOST_IP}"
    env_file:
      - env.prod
# networks:
# default:
# name: finance-net
